### ISSUE TITLE
'isReferencing' relations are not up to date after import of content

### ISSUE THREAD

**Issue by ksuess** [plone/plone.exportimport#32]
See demo.plone.org relations control panel.

I suggest to either 
include `isReferencing` relations in importing the exported relations (see RELATIONS_TO_IGNORE)
or update the relations with plone.app.linkintegrity 'modifiedContent' after importing content.

@ericof Please open repo for creating branch. Thanks!

**Comment by ericof** [comment]
@ksuess You should be able to create branches now
